Abort commit when Makefile is not found.
Instead of just printing an error message and committing either way
abort the commit. Else the user may falsely assume the hook was properly
executed. Print the location where the path has to be changed and the
--no-verify option to skip hooks as well.

diff --git a/pre-commit-compile b/pre-commit-compile
--- a/pre-commit-compile
+++ b/pre-commit-compile
@@ -18,7 +18,10 @@ if [ -f $MAKEFILE ] ; then
     fi
     echo "Build success."
 else
-    echo "Error: Makefile not found."
+    echo "Error: Makefile not found. Aborting commit."
+    echo "Set the correct path in $(readlink -f $0)."
+    echo "Skip pre-commit hooks with --no-verify (not recommended)."
+    exit 1
 fi
 
 exit 0
