Cancel commit if one of the specified pre-commit hooks is not found.
Else the user may not realise something is missing. Print a hint where
the hook has to be placed and that it has be executable as well. And for
good measure how to skip the hooks.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -26,5 +26,8 @@ do
         fi
     else
         echo "Error: file $hook not found."
+        echo "Aborting commit. Make sure the hook is in $SCRIPTPATH and executable."
+        echo "You can skip the pre-commit hooks with --no-verify (not recommended)."
+        exit 1
     fi
 done
